{"uuid": "4b7c2984-9caf-49f5-b1dc-a5dde9fd766d", "children": ["3922a70e-8b9b-4650-9af3-9b38c47ce173"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 126\nCurrent browser version is 123.0.6312.105 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x64b7b8686c5a <unknown>\n#1 0x64b7b8369e2c <unknown>\n#2 0x64b7b83a58db <unknown>\n#3 0x64b7b83a4a82 <unknown>\n#4 0x64b7b839f0a1 <unknown>\n#5 0x64b7b839b17b <unknown>\n#6 0x64b7b83e5c49 <unknown>\n#7 0x64b7b83d9363 <unknown>\n#8 0x64b7b83a9247 <unknown>\n#9 0x64b7b83a9b9e <unknown>\n#10 0x64b7b864d22b <unknown>\n#11 0x64b7b86512d1 <unknown>\n#12 0x64b7b8638ade <unknown>\n#13 0x64b7b8651e32 <unknown>\n#14 0x64b7b861d77f <unknown>\n#15 0x64b7b8676618 <unknown>\n#16 0x64b7b86767f0 <unknown>\n#17 0x64b7b8685d8c <unknown>\n#18 0x7144b9494ac3 <unknown>\n\n", "trace": "  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/fuenukkusu2501/Develop/tmp/OTUS_selenium_UI/conftest.py\", line 56, in browser\n    browser = webdriver.Chrome(service=Service(), options=options)\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 61, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1721480745056, "stop": 1721480754181}], "start": 1721480745056, "stop": 1721480754320}