[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x71c526230e30>: Failed to resolve 'selenoid' ([Errno -3] Temporary failure in name resolution)")': /wd/hub/session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x71c526233f50>: Failed to resolve 'selenoid' ([Errno -3] Temporary failure in name resolution)")': /wd/hub/session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x71c526231ee0>: Failed to resolve 'selenoid' ([Errno -3] Temporary failure in name resolution)")': /wd/hub/session